### PR TITLE
Fix Windows compilation

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by JimmyDaSilva** [comment]
Hi @Tobias-Fischer.
I tried using your branch on my Windows 10 with Qt 5.12.2 and compiler VS2015_x64, but I still got some errors related to <string_view> and qOverload:
```
2>F:\PlotJuggler\plugins\DataStreamUDP\udp_server.cpp(107): error C2065: 'qOverload': undeclared identifier
2>F:\PlotJuggler\plugins\DataStreamUDP\udp_server.cpp(107): error C2059: syntax error: 'const'
2>F:\PlotJuggler\plugins\DataStreamUDP\udp_server.cpp(109): error C2143: syntax error: missing ';' before '{'
2>F:\PlotJuggler\plugins\DataStreamUDP\udp_server.cpp(119): error C2059: syntax error: ')'
3>F:\PlotJuggler\plugins\DataStreamWebsocket\websocket_server.cpp(109): error C2065: 'qOverload': undeclared identifier
3>F:\PlotJuggler\plugins\DataStreamWebsocket\websocket_server.cpp(109): error C2059: syntax error: 'const'
3>F:\PlotJuggler\plugins\DataStreamWebsocket\websocket_server.cpp(111): error C2143: syntax error: missing ';' before '{'
3>F:\PlotJuggler\plugins\DataStreamWebsocket\websocket_server.cpp(121): error C2059: syntax error: ')'
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(17): warning C4996: 'qrand': use QRandomGenerator instead
4>  F:\Qt\5.15.2\msvc2015_64\include\QtCore/qglobal.h(1279): note: see declaration of 'qrand'
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(226): error C2065: 'qOverload': undeclared identifier
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(226): error C2059: syntax error: 'const'
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(228): error C2143: syntax error: missing ';' before '{'
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(233): error C2065: 'protocol': undeclared identifier
4>F:\PlotJuggler\plugins\DataStreamMQTT\datastream_mqtt.cpp(238): error C2059: syntax error: ')'
5>  custom_function.cpp
5>F:\PlotJuggler\3rdparty\sol\sol.hpp(618): fatal error C1083: Cannot open include file: 'string_view': No such file or directory
5>  custom_timeseries.cpp
5>F:\PlotJuggler\3rdparty\sol\sol.hpp(618): fatal error C1083: Cannot open include file: 'string_view': No such file or directory
5>  function_editor.cpp
5>F:\PlotJuggler\3rdparty\sol\sol.hpp(618): fatal error C1083: Cannot open include file: 'string_view': No such file or directory
5>  lua_custom_function.cpp
5>F:\PlotJuggler\3rdparty\sol\sol.hpp(618): fatal error C1083: Cannot open include file: 'string_view': No such file or directory
5>  moving_average_filter.cpp
5>F:\PlotJuggler\src\transforms\moving_average_filter.cpp(13): error C2065: 'qOverload': undeclared identifier
5>F:\PlotJuggler\src\transforms\moving_average_filter.cpp(13): error C2062: type 'int' unexpected
5>F:\PlotJuggler\src\transforms\moving_average_filter.cpp(14): error C2143: syntax error: missing ';' before '{'
5>F:\PlotJuggler\src\transforms\moving_average_filter.cpp(14): error C2059: syntax error: ')'
5>  outlier_removal.cpp
5>F:\PlotJuggler\src\transforms\outlier_removal.cpp(12): error C2065: 'qOverload': undeclared identifier
5>F:\PlotJuggler\src\transforms\outlier_removal.cpp(12): error C2062: type 'double' unexpected
5>F:\PlotJuggler\src\transforms\outlier_removal.cpp(13): error C2143: syntax error: missing ';' before '{'
5>F:\PlotJuggler\src\transforms\outlier_removal.cpp(13): error C2059: syntax error: ')'
```

Do I need a specific version of Qt5/Compiler?

Thanks !

**Comment by Tobias-Fischer** [comment]
Hi, I'm not sure what's going wrong there. We used VS2017 with QT5.12. To get all the dependencies, we used conda, but I'm not sure why that would make a difference. Google searches hint towards using C++14, maybe enable that when compiling.

**Comment by Tobias-Fischer** [comment]
Oh, and you can always `conda install ros-noetic-plotjuggler -c robostack` to make your life easier.

**Comment by JimmyDaSilva** [comment]
Thanks @Tobias-Fischer. It worked with VS2017 with QT5.12 without adding any specific compiler arguments

**Comment by facontidavide** [comment]
I made a different change and it compiles in both VS2017 and VS2019.

What was the purpose of this part ?

```
if (WIN32)
  add_definitions(-DQT_NO_FLOAT16_OPERATORS)
endif()
```

**Comment by Tobias-Fischer** [comment]
You can read about that change here: https://doc.qt.io/qt-5/qfloat16.html#QT_NO_FLOAT16_OPERATORS
